package org.ccci.idm.user;

public interface Constants {
    // base strength values
    double STRENGTH_NONE = 0.0;
    double STRENGTH_FULL = 1.0;

    // Audit constants
    String AUDIT_ACTION_RESOLVER_USER_MANAGER = "IDM_USER_MANAGER_ACTION_RESOLVER";

    String AUDIT_ACTION_CREATE_USER = "IDM_CREATE_USER";
    String AUDIT_ACTION_UPDATE_USER = "IDM_UPDATE_USER";
    String AUDIT_ACTION_DEACTIVATE_USER = "IDM_DEACTIVATE_USER";
    String AUDIT_ACTION_REACTIVATE_USER = "IDM_REACTIVATE_USER";
    String AUDIT_ACTION_ADD_TO_GROUP = "IDM_ADD_TO_GROUP";
    String AUDIT_ACTION_REMOVE_FROM_GROUP = "IDM_REMOVE_FROM_GROUP";

    String AUDIT_RESOURCE_RESOLVER_CREATE_USER = "IDM_USER_MANAGER_CREATE_USER_RESOURCE_RESOLVER";
    String AUDIT_RESOURCE_RESOLVER_UPDATE_USER = "IDM_USER_MANAGER_UPDATE_USER_RESOURCE_RESOLVER";
    String AUDIT_RESOURCE_RESOLVER_DEACTIVATE_USER = "IDM_USER_MANAGER_DEACTIVATE_USER_RESOURCE_RESOLVER";
    String AUDIT_RESOURCE_RESOLVER_REACTIVATE_USER = "IDM_USER_MANAGER_REACTIVATE_USER_RESOURCE_RESOLVER";
    String AUDIT_RESOURCE_RESOLVER_ADD_TO_GROUP = "IDM_USER_MANAGER_ADD_TO_GROUP_RESOURCE_RESOLVER";
    String AUDIT_RESOURCE_RESOLVER_REMOVE_FROM_GROUP = "IDM_USER_MANAGER_REMOVE_FROM_GROUP_RESOURCE_RESOLVER";
}
